export var emojiDictionary = {
  "🍏": "Green Apple",
  "🍎": "Red Apple",
  "🍐": "Pear",
  "🍊": "Tangerine",
  "🍋": "Lemon",
  "🍌": "Banana",
  "🍉": "Watermelon",
  "🍇": "Grapes",
  "🍓": "Strawberry",
  "🍈": "Melon",
  "🍒": "Cherries",
  "🍑": "Peach",
  "🥭": "Mango",
  "🍍": "Pineapple",
  "🥥": "Coconut",
  "🥑": "Avocado",
  "🥦": "Broccoli",
  "🥬": "Leafy Veggie",
  "🍅": "Tomato",
  "🍆": "Eggplant",
  "🥕": "Carrot",
  "🌶": "Red Pepper",
  "🌽": "Corn",
  "🍠": "Sweet Potato",
  "🥯": "Bagel",
  "": ""
};
